---
apiVersion: v1
kind: Service
metadata:
  name: hello1
spec:
  selector:
    app: hello
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello2
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 4
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: leonidosl/hello:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
